// auth
export const AUTH_REQUEST  = 'AUTH_REQUEST'
export const AUTH_SUCCESS  = 'AUTH_SUCCESS'
export const AUTH_FAILURE  = 'AUTH_FAILURE'
export const DISMISS_AUTH_ERROR  = 'DISMISS_AUTH_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// Workouts
export const FETCH_WORKOUTS_REQUEST = 'FETCH_WORKOUTS_REQUEST'
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS'
export const FETCH_WORKOUTS_FAILURE = 'FETCH_WORKOUTS_FAILURE'

// Custom workoutList
export const FETCH_CUSTOM_WORKOUTS_REQUEST  = 'FETCH_CUSTOM_WORKOUTS_REQUEST'
export const FETCH_CUSTOM_WORKOUTS_SUCCESS  = 'FETCH_CUSTOM_WORKOUTS_SUCCESS'
export const FETCH_CUSTOM_WORKOUTS_FAILURE  = 'FETCH_CUSTOM_WORKOUTS_FAILURE'
export const ADD_CUSTOM_WORKOUT_SUCCESS     = 'ADD_CUSTOM_WORKOUT_SUCCESS'
export const ADD_CUSTOM_WORKOUT_FAILURE     = 'ADD_CUSTOM_WORKOUT_FAILURE'

// Exercises
export const FETCH_EXERCISES_REQUEST = 'FETCH_EXERCISES_REQUEST'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_FAILURE = 'FETCH_EXERCISES_FAILURE'

// Create Workout Form
export const CREATE_WORKOUT_RESET                   = 'CREATE_WORKOUT_RESET'
export const CREATE_WORKOUT_SET_VALUE               = 'CREATE_WORKOUT_SET_VALUE'
export const CREATE_WORKOUT_ADD_EXERCISE            = 'CREATE_WORKOUT_ADD_EXERCISE'
export const CREATE_WORKOUT_REMOVE_EXERCISE         = 'CREATE_WORKOUT_REMOVE_EXERCISE'
export const CREATE_WORKOUT_ADD_EXERCISE_SET        = 'CREATE_WORKOUT_ADD_EXERCISE_SET'
export const CREATE_WORKOUT_REMOVE_EXERCISE_SET     = 'CREATE_WORKOUT_REMOVE_EXERCISE_SET'
export const CREATE_WORKOUT_SET_EXERCISE_SET_VALUE  = 'CREATE_WORKOUT_SET_EXERCISE_SET_VALUE'

// Cardio Presets
export const FETCH_CARDIO_PRESETS_REQUEST = 'FETCH_CARDIO_PRESETS_REQUEST'
export const FETCH_CARDIO_PRESETS_SUCCESS = 'FETCH_CARDIO_PRESETS_SUCCESS'
export const FETCH_CARDIO_PRESETS_FAILURE = 'FETCH_CARDIO_PRESETS_FAILURE'

// Workout Logs
export const FETCH_WORKOUT_LOGS_REQUEST = 'FETCH_WORKOUT_LOGS_REQUEST'
export const FETCH_WORKOUT_LOGS_SUCCESS = 'FETCH_WORKOUT_LOGS_SUCCESS'
export const FETCH_WORKOUT_LOGS_FAILURE = 'FETCH_WORKOUT_LOGS_FAILURE'

// Cardio Logs
export const FETCH_CARDIO_LOGS_REQUEST = 'FETCH_CARDIO_LOGS_REQUEST'
export const FETCH_CARDIO_LOGS_SUCCESS = 'FETCH_CARDIO_LOGS_SUCCESS'
export const FETCH_CARDIO_LOGS_FAILURE = 'FETCH_CARDIO_LOGS_FAILURE'

// WorkoutSession
export const CONSTRUCT_SESSION          = "CONSTRUCT_SESSION"
export const TOGGLE_PAUSE_SESSION       = "TOGGLE_PAUSE_SESSION"
export const INCREMENT_SECONDS_ELAPSED  = "INCREMENT_SECONDS_ELAPSED"
export const INCREMENT_CURRENT_SET      = "INCREMENT_CURRENT_SET"
export const DECREMENT_CURRENT_SET      = "DECREMENT_CURRENT_SET"
export const UPDATE_CURRENT_SET_VALUES  = "UPDATE_CURRENT_SET_VALUES"
export const CLEAR_SESSION              = "CLEAR_SESSION"

// CardioSession
export const UPDATE_CARDIO_SESSION_CONFIGURATION  = 'UPDATE_CARDIO_SESSION_CONFIGURATION'
export const ADD_CARDIO_BOT                       = 'ADD_CARDIO_BOT'
export const UPDATE_CARDIO_BOT_CONFIGURATION      = 'UPDATE_CARDIO_BOT_CONFIGURATION'
export const UPDATE_CARDIO_BOT_INTERVALS          = 'UPDATE_CARDIO_BOT_INTERVALS'
export const REMOVE_CARDIO_BOT                    = 'REMOVE_CARDIO_BOT'
export const TOGGLE_PAUSE_CARDIO_SESSION          = 'TOGGLE_PAUSE_CARDIO_SESSION'
export const INCREMENT_CARDIO_SECONDS_ELAPSED     = 'INCREMENT_CARDIO_SECONDS_ELAPSED'
export const ADD_TRACKED_INTERVAL                 = 'ADD_TRACKED_INTERVAL'
export const CLEAR_CARDIO_SESSION                 = 'CLEAR_CARDIO_SESSION'

// Configuration
export const FETCH_CONFIGURATION_REQUEST        = "FETCH_CONFIGURATION_REQUEST"
export const FETCH_CONFIGURATION_SUCCESS        = "FETCH_CONFIGURATION_SUCCESS"
export const FETCH_CONFIGURATION_FAILURE        = "FETCH_CONFIGURATION_FAILURE"

// aggregated reps
export const FETCH_AGGREGATED_REPS_REQUEST      = "FETCH_AGGREGATED_REPS_REQUEST"
export const FETCH_AGGREGATED_REPS_SUCCESS      = "FETCH_AGGREGATED_REPS_SUCCESS"
export const FETCH_AGGREGATED_REPS_FAILURE      = "FETCH_AGGREGATED_REPS_FAILURE"

// aggregated cardio times
export const FETCH_AGGREGATED_CARDIO_TIMES_REQUEST      = "FETCH_AGGREGATED_CARDIO_TIMES_REQUEST"
export const FETCH_AGGREGATED_CARDIO_TIMES_SUCCESS      = "FETCH_AGGREGATED_CARDIO_TIMES_SUCCESS"
export const FETCH_AGGREGATED_CARDIO_TIMES_FAILURE      = "FETCH_AGGREGATED_CARDIO_TIMES_FAILURE"

// aggregated max lifts
export const FETCH_AGGREGATED_MAX_LIFTS_REQUEST      = "FETCH_AGGREGATED_MAX_LIFTS_REQUEST"
export const FETCH_AGGREGATED_MAX_LIFTS_SUCCESS      = "FETCH_AGGREGATED_MAX_LIFTS_SUCCESS"
export const FETCH_AGGREGATED_MAX_LIFTS_FAILURE      = "FETCH_AGGREGATED_MAX_LIFTS_FAILURE"
export const UPDATE_AGGREGATED_MAX_LIFTS_FILTER      = "UPDATE_AGGREGATED_MAX_LIFTS_FILTER"
export const UPDATE_AGGREGATED_MAX_LIFTS_VISIBILITY_FILTER = "UPDATE_AGGREGATED_MAX_LIFTS_VISIBILITY_FILTER"

// aggregated max lifts
export const FETCH_AGGREGATED_SPEEDS_REQUEST      = "FETCH_AGGREGATED_SPEEDS_REQUEST"
export const FETCH_AGGREGATED_SPEEDS_SUCCESS      = "FETCH_AGGREGATED_SPEEDS_SUCCESS"
export const FETCH_AGGREGATED_SPEEDS_FAILURE      = "FETCH_AGGREGATED_SPEEDS_FAILURE"
export const UPDATE_AGGREGATED_SPEEDS_FILTER      = "UPDATE_AGGREGATED_SPEEDS_FILTER"
export const UPDATE_AGGREGATED_SPEEDS_VISIBILITY_FILTER = "UPDATE_AGGREGATED_SPEEDS_VISIBILITY_FILTER"
